GET http://localhost:3001/dockits

###

POST http://localhost:3001/dockit/new
Content-Type: application/json

{
    "text": "Go to Gym"
}

###

DELETE http://localhost:3001/dockit/delete/643136477c7ba1b8668636db

###

PUT http://localhost:3001/dockit/complete/643135bb1164706aad19ca7a